openapi: 3.0.1
info:
  $ref:  ./swagger_doc/info.yaml
externalDocs:
  description: Find out more about Swagger
url: http://swagger.io
servers:
 - url: http://localhost:3000/api
   description: Internal staging server for testing
 - url: https://localhost:3000/api
   description: Main (production) server
 - url: https://node-posts-api-web.herokuapp.com/api
   description: Heroku server
paths:
  /auth/login:
    $ref: "./swagger_doc/paths/auth/login.yaml"
  /auth/register:
    $ref: "./swagger_doc/paths/auth/register.yaml"
  /auth/gmail_login:
    $ref: "./swagger_doc/paths/auth/gmail_login.yaml"
  /auth/fb_login:
    $ref: "./swagger_doc/paths/auth/fb_login.yaml"
  /post/upload_files:
    $ref: "./swagger_doc/paths/post/upload_file.yaml"
  /post/create:
    $ref: "./swagger_doc/paths/post/create.yaml"
  /post/edit/{postId}:
    $ref: "./swagger_doc/paths/post/edit.yaml"
  /post/show/{postId}:
    $ref: "./swagger_doc/paths/post/show.yaml"
  /post/delete/{postId}:
    $ref: "./swagger_doc/paths/post/delete.yaml"
  /post/{postId}/file/{fileId}:
    $ref: "./swagger_doc/paths/post/delete_file.yaml"
  /post/{postId}/comment:
    $ref: "./swagger_doc/paths/post/comment.yaml"
  /post/user:
    $ref: "./swagger_doc/paths/post/user_post.yaml"
  /post:
    $ref: "./swagger_doc/paths/post/all_post.yaml"
  /user/upload_profile_image:
    $ref: "./swagger_doc/paths/user/upload_image.yaml"
  /user/profile:
    $ref: "./swagger_doc/paths/user/user_profile.yaml"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    $ref: "./swagger_doc/components/responses.yaml"
  schemas:
    $ref: "./swagger_doc/components/schemas.yaml"
